default: &default
  #host: /tmp
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pgapp_development
  host: localhost

test:
  <<: *default
  database: pgapp_test

production:
  host: localhost
  adapter: postgresql
  username: goalista
  password: 
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
